

# R: moddified config using batch outside of training_parameters and set to 1
save_dir: save/
model_name: VT5
# model_weights: t5-base
# model_weights: weights/t5_oracle_mp-docvqa__best.ckpt
model_weights: rubentito/vt5-base-spdocvqa
max_source_length: 512
device: cuda
data_parallel: False
batch_size: 1

training_parameters:
  lr: 2e-4  # 2e-4
  # batch_size: 32
  train_epochs: 10
  warmup_iterations: 1000

# visual_module:
#   model: 'dit'  # 'vit' / 'dit'
#   finetune: false
#   model_weights: 'microsoft/dit-base-finetuned-rvlcdip'  # 'google/vit-base-patch16-224-in21k' / 'microsoft/dit-base-finetuned-rvlcdip'




visual_module:
  model: 'vit'
  finetune: false
  model_weights: 'google/vit-base-patch16-224-in21k'